AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Enabled: false
