Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Enabled: false
