name: "Linter"
on: 
  push:

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1.2'
          # Используем гемы из кэша вместо того чтобы устанавливать их заново
          bundler-cache: true

      - name: Lint Ruby files
        run: bundle e rubocop --parallel
